### PR TITLE
Updated laravel 7.x dependencies

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by iben12** [comment]
Composer installation causes some very strange issue in Travis CI. Has to do something with the carbon package. I haven't seen such before: https://travis-ci.org/github/iben12/laravel-statable/jobs/663011015

Any insights anyone?

**Comment by Skullbock** [comment]
I think it's a caching issue in travis. Is there a way to trigger a clean rebuild instal of reusing the cache of the previous runs?

**Comment by Skullbock** [comment]
see: https://github.com/briannesbitt/Carbon/issues/1773

**Comment by iben12** [comment]
OK, I deleted the caches and the build runs now. Could you pls check the failed test?

**Comment by Skullbock** [comment]
Should've fixed it ;)

**Pull request merged**
