### PR TITLE
Small addition to PR #26

### PR DESCRIPTION
**Pull request by vpratfr**
Forgot to publish config file

### CODE REVIEW

**Comment by vpratfr** [comment]
Sorry, I did not expect #26 to get merged that fast.

**Comment by iben12** [comment]
Yeah, understandable :D

I also did not check it the config thoroughly enough.

Seems like you have to rebase to master however, now that I merged it in between. Sorry.

**Comment by vpratfr** [comment]
Should be fine now. That can be merged

**Comment by vpratfr** [comment]
Hi, any chance that could be merged and a new release tagged before week ends? Currently takling the code that hits this issue on our project.

**Comment by iben12** [comment]
Had resolve some conflicts and then merged it offline. Thanks @vpratfr

**Comment by vpratfr** [comment]
Sorry about the crappy PR :) Thanks a lot for the package!

**Pull request closed without merging**
